//! WinUI 3 (Windows) backend for mitsuami.
//!
//! - Driven imperatively through our own `windows-bindgen` bindings
//!   (`src/bindings.rs`, regenerated by the tool in `bindgen/`). No
//!   `windows-reactor` at runtime.
//! - Containers are `Canvas`es that do no layout of their own; the core
//!   positions every child with `Canvas.Left/Top` and `Width/Height`.
//! - Leaf widgets are stock WinUI controls, measured with `Measure` in the
//!   live tree, with the frame size we imposed lifted for the call.
//! - Escape hatches: [`tweak`] for raw settings of built-in controls,
//!   [`NativeRender`] for custom widgets, [`NativeView`] for any XAML
//!   element, and XAML shapes for drawn custom widgets.
//! - [`run`] runs XAML's event loop, without `Application::Start`, and
//!   ticks the UI from its dispatcher queue.
//!
//! Needs the Windows App Runtime 2.4 or later installed, and the MSVC
//! toolchain (`x86_64-pc-windows-msvc` or `aarch64-pc-windows-msvc`).

#[cfg(all(windows, not(target_env = "msvc")))]
compile_error!(concat!(
    "mitsuami on Windows needs the MSVC toolchain (x86_64-pc-windows-msvc). ",
    "Make it the default once with `rustup set default-host x86_64-pc-windows-msvc`, ",
    "or build with `cargo +1.96-x86_64-pc-windows-msvc ...`."
));

#[cfg(all(windows, target_env = "msvc"))]
mod app;
#[cfg(all(windows, target_env = "msvc"))]
mod backend;
/// The generated WinUI bindings (see `bindgen/filter.txt`): the escape
/// hatch for reaching the native widgets, like `objc2` types on AppKit. They
/// cover what this crate uses, not all of WinUI.
#[cfg(all(windows, target_env = "msvc"))]
#[allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    unused_qualifications,
    clippy::all,
    missing_debug_implementations,
    missing_docs
)]
pub mod bindings;
#[cfg(all(windows, target_env = "msvc"))]
mod capture;
#[cfg(all(windows, target_env = "msvc"))]
mod custom;
#[cfg(all(windows, target_env = "msvc"))]
mod double_click;
#[cfg(all(windows, target_env = "msvc"))]
mod drop;
#[cfg(all(windows, target_env = "msvc"))]
mod file_icon;
#[cfg(all(windows, target_env = "msvc"))]
mod group;
#[cfg(all(windows, target_env = "msvc"))]
mod hover;
#[cfg(all(windows, target_env = "msvc"))]
mod later;
#[cfg(all(windows, target_env = "msvc"))]
mod list;
#[cfg(all(windows, target_env = "msvc"))]
mod locale;
#[cfg(all(windows, target_env = "msvc"))]
mod runtime;
#[cfg(all(windows, target_env = "msvc"))]
mod services;
#[cfg(all(windows, target_env = "msvc"))]
mod session;
#[cfg(all(windows, target_env = "msvc"))]
mod sidebar;
#[cfg(all(windows, target_env = "msvc"))]
mod surface;
#[cfg(all(windows, target_env = "msvc"))]
mod tabs;
#[cfg(all(windows, target_env = "msvc"))]
mod tweak;

#[cfg(all(windows, target_env = "msvc"))]
pub use app::{init_for_tests, pump, run, set_menu_bar_place, set_toolbar_place, set_window_placement};
#[cfg(all(windows, target_env = "msvc"))]
pub use backend::{
    BackendOptions, MenuBarPlace, ToolbarAlign, ToolbarPlace, WinUiBackend, WinUiHandle, WindowPlacement,
};
#[cfg(all(windows, target_env = "msvc"))]
pub use custom::{Emitter, NativeRender, NativeView, WinUiCx, ad_hoc, native};
#[cfg(all(windows, target_env = "msvc"))]
pub use services::WinUiServices;
#[cfg(all(windows, target_env = "msvc"))]
pub use tweak::{Tweakable, remove_item_animations, tweak, tweak_with, without_item_animations};

// What native renders and native views are written with, at the versions
// the backend uses: `cast`, `Result`, event revokers, and collections to
// fill an `ItemsSource` with.
#[cfg(all(windows, target_env = "msvc"))]
pub use {windows_collections, windows_core};
